# Generated by Django 5.1.2 on 2024-11-04 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='category',
            field=models.CharField(choices=[('tanks', 'Танки'), ('healers', 'Хилы'), ('dd', 'ДД'), ('traders', 'Торговцы'), ('guild_masters', 'Гилдмастеры'), ('Quest Givers', 'КвестГиверы'), ('Kuznetsov', 'Кузнеци'), ('Tanners', 'Кожевники'), ('Potion Makers', 'Зельевары'), ('Spell Masters', 'Мастера заклинаний')], default='tanks', max_length=20),
        ),
        migrations.AddField(
            model_name='ads',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
